theme: jekyll-theme-minimal
title: 'RNA-Seq Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_May_2020.pdf
  - title: Experimental Design and Cost Estimation
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/mrna/mRNAseq-expDesign_May_2020.pdf
  - title: RNA Sequencing Technologies - Dr. Lutz Froenicke
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/mrna/Lutz_Froenicke_RNASeq_2021.pdf

  - heading: Support
  - title: Zoom
    url: base/zoom
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Prepare dataset
    url: data_reduction/00-project_setup_mm
  - title: Preprocessing raw data
    url: data_reduction/01-preproc_htstream_mm
  - title: Indexing a Genome
    url: data_reduction/02-alignment-indexref_mm
  - title: Alignment with Star
    url: data_reduction/02-alignment_mm
  - title: Generating counts tables
    url: data_reduction/03-counts_mm
  - title: Alignment/Counts with Salmon (Extra)
    url: data_reduction/02-salmon_mm

  - heading: Data analysis
  - title: Prepare R for data analysis
    url: data_analysis/de_analysis_prepare_mm
  - title: Annotation from BioMart
    url: data_analysis/annotation_mm
  - title: Differential Expression Analysis
    url: data_analysis/DE_Analysis_mm_with_quizzes
  - title: Pathway Analysis
    url: data_analysis/enrichment_mm_with_quizzes
  - title: Comparison between STAR and Salmon
    url: data_analysis/compare_star_salmon_mm

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-September-RNA-Seq-Analysis
  - title: Report Errors
    url: https://github.com/ucdavis-bioinformatics-training/2021-September-RNA-Seq-Analysis/issues
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
